name: "Terraform CI Pratice"
on: 
  push:
    branches:
      - feature/Iac_01
  pull_request:
    branches:
      - feature/Iac_01
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs: 
  terraform: 
    name: "Terraform provision Pratice"
    runs-on: ubuntu-latest
    steps:
      #check out the terraform repo code test
      - name: 'Checkout tf source code'
        uses: actions/checkout@v3
      
      # setup terraform cli 
      - name: "TF enginee Setup"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
          terraform_wrapper: false

      - name: "Create namespace"
        run: "terraform workspace new dev"
        continue-on-error: true
        
      - name: "Select namespace"
        run: "terraform workspace select dev"
        continue-on-error: true

      - name: "Init tf"
        run: |
          terraform init -backend-config=dev.conf
          
      # - name: "Destroy the resources"
      #   run: "terraform destroy --auto-approve"
      - name: "Verify the tfvars "
        run: "terraform plan -var-file=./envs/dev.tfvars"

      - name: "apply the tfvars "
        run: "terraform destroy  -var-file=./envs/dev.tfvars --auto-approve"
       